version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    command: >
      -c max_connections=25
    restart: always
    env_file:
      - .env
  contents:
    image: motxx/aperture-lnproxy-contents
    platform: linux/amd64
    build: ./contents
    restart: always
    env_file:
      - ./contents/.env
    ports:
      - "8080:8080"
  lnproxy:
    image: motxx/aperture-lnproxy-lnproxy
    platform: linux/amd64
    build: ./lnproxy
    restart: always
    volumes:
      - ./.lnd:/root/.lnd
    env_file:
      - ./lnproxy/.env
  aperture:
    image: motxx/aperture-lnproxy-aperture
    platform: linux/amd64
    build: ./aperture
    restart: always
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
      - contents
      - lnproxy
    env_file:
      - ./aperture/.env
    volumes:
      - ./.lnd:/root/.lnd
      - ./config:/root/config
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/fullchain.pem:/etc/nginx/cert/fullchain.pem
      - ./nginx/ssl/privkey.pem:/etc/nginx/cert/privkey.pem
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - aperture
