version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./db/logs:/var/log
      - ./db/postgres/data:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d
    command: >
      -c max_connections=25
    restart: always
    env_file:
      - .env
  contents:
    platform: linux/amd64
    build: ./contents
    restart: always
    env_file:
      - .env
      - ./contents/.env
    ports:
      - "8080:8080"
  lnproxy:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./lnproxy/dockerfile.lnproxy
    restart: always
    volumes:
      - ./.lnd:/root/.lnd
    env_file:
      - ./lnproxy/.env
  aperture:
    platform: linux/amd64
    build: ./aperture
    restart: always
    depends_on:
      - db
      - contents
      - lnproxy
    env_file:
      - ./aperture/.env
    volumes:
      - ./.lnd:/root/.lnd
      - ./config:/root/config
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/fullchain.pem:/etc/nginx/cert/fullchain.pem
      - ./nginx/ssl/privkey.pem:/etc/nginx/cert/privkey.pem
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - aperture
